### ISSUE TITLE
metrics_task2_bug

### ISSUE THREAD

**Issue by Voyager-Aura** [l3das/L3DAS22#1]
When len(t) == 0 and len(p) == 0，FN and FP were added twice. It results in that TP+FN is not a constant when tested with different results.

**Comment by l3das** [comment]
Hello @zengying-cqupt, 
thanks for your interest in the L3DAS22 challenge.
We have double checked the location_sensitive_detection function and it is correct. When the condition you mention happens (len(t) == 0 and len(p) == 0)，only zeros are added to FN and FP. 
At lines 155-157 we add zeros, as len(p) and len(t) are 0. At lines 180-182 we also add zeros as matched remains 0 and therefore also fn and fp remain 0.
We hope to have clarified your doubt.

**Comment by Voyager-Aura** [comment]
Thanks for your reply @l3das , when len(t) == 0 and len(p) !=0, FP was added len(p) at lines 155, and FP was also added len(p) at lines 182, it was added twice in same time frame.  When len(p) == 0 and len(t) !=0, FN was added len(t) at lines 157,  and was added a second time on line 181. 
And when the same event occurs in two different directions in the same time frame, like label_split4_ov3_44(19s-20s), if the model predicts only one event, matched =2( if spat_error < spatial_threshold ) , FP will be -1 and FN will be 0.
These have a little impact on the final indicators.

**Comment by l3das** [comment]
Hi @zengying-cqupt,
As regards the conditions len(t) == 0 and len(p) !=0 and vice-versa there was an indentation error and now it is fixed.  Instead, as regards the other case you describe (the same event occurs in two different directions in the same time frame, if the model predicts only one event), we double checked the code recreating this condition and we confirm that this only happened when the true events were simultaneous and within the spatial_threshold. We have now fixed this. This had an impact of 0.01 on the baseline test F-Score metric. Thanks for spotting these bugs! Could you please check again and confirm if everything is working fine now on your side?

**Comment by Voyager-Aura** [comment]
Thanks, everything is working fine now.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l3das/L3DAS22"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上10:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l3das/L3DAS22] metrics_task2_bug (Issue #1)





 
Hi @zengying-cqupt,
 As regards the conditions len(t) == 0 and len(p) !=0 and vice-versa there was an indentation error and now it is fixed.  Instead, as regards the other case you describe (the same event occurs in two different directions in the same time frame, if the model predicts only one event), we double checked the code recreating this condition and we confirm that this only happened when the true events were simultaneous and within the spatial_threshold. We have now fixed this. Thanks for spotting these bugs! Could you please check again and confirm if everything is working fine now on your side?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by l3das** [comment]
Thanks to you

**Comment by zengying-cqupt** [comment]
Hello, when the same event occurs in two(Three) different directions in the same time frame, if the model predicts Correctly，matched = matched - duplicates = 2 -&nbsp; 2 = 0(matched =&nbsp;matched - duplicates = 3 - 6 = -3).
Let matched = len(unique_ids) can solve this bug.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l3das/L3DAS22"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l3das/L3DAS22] metrics_task2_bug (Issue #1)





 
Thanks to you
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Voyager-Aura** [comment]
Hello, when the same event occurs in two(Three) different directions in the same time frame, if the model predicts Correctly，matched = matched - duplicates = 2 -&nbsp; 2 = 0(matched = matched - duplicates = 3 - 6 = -3).
Let matched = len(unique_ids) can solve this bug.
To avoid&nbsp;len(unique_ids)&nbsp;&gt; matched(Calculated on line 178),&nbsp;I added a condition on line 182.






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "l3das/L3DAS22"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月10日(星期五) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l3das/L3DAS22] metrics_task2_bug (Issue #1)





 
Thanks to you
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by l3das** [comment]
Hello @zengying-cqupt ,
We have found a simpler solution and updated the code. Thanks for spotting this.
